const DATA={
 popular:[['solo','Solo Leveling','Action · Adventure','2.4M','9.8'],['one','One Piece','Action · Adventure','1.8M','9.7'],['blue','Blue Lock','Sports · Psychological','1.2M','9.5'],['jjk','Jujutsu Kaisen','Action · Supernatural','1.5M','9.6'],['tba','The Beginning After The End','Action · Fantasy','908K','9.4'],['mage','Versatile Mage','Action · Fantasy','760K','9.3']],
 manhwa:[['hua','Return of the Mount Hua','Action · Murim','1.1M','9.6'],['extra',"The Extra's Academy Survival Guide",'Fantasy · School','840K','9.5'],['villain',"I Became the Villain's Son",'Drama · Fantasy','620K','9.2'],['sss','SSS-Class Suicide Hunter','Action · Fantasy','780K','9.7'],['infinite','Infinite Mage','Fantasy · Magic','540K','9.3'],['tower','Tower of God','Adventure · Fantasy','650K','9.1']],
 novel:[['reverend','Reverend Insanity','Action · Fantasy','1.2M','9.6'],['mysteries','Lord of the Mysteries','Mystery · Supernatural','980K','9.5'],['orv','Omniscient Reader','Action · Fantasy','860K','9.4'],['moon','The Legendary Moonlight Sculptor','Action · Fantasy','760K','9.3'],['demons','Tales of Demons and Gods','Action · Fantasy','690K','9.2'],['martial','Martial Peak','Action · Adventure','620K','9.1']]
};
const palettes=['linear-gradient(145deg,#101d55,#1468ff,#00d8ff)','linear-gradient(145deg,#8e1b18,#ffae22,#1679ff)','linear-gradient(145deg,#071f67,#1b68ff,#17c8ff)','linear-gradient(145deg,#240b38,#a62660,#ff5b30)','linear-gradient(145deg,#18344e,#50a8a9,#c6ecff)','linear-gradient(145deg,#2a174b,#3b64ff,#ffb4ff)'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={favorites:JSON.parse(localStorage.getItem('nt_favorites')||'[]'),history:JSON.parse(localStorage.getItem('nt_history')||'[]'),reader:localStorage.getItem('nt_reader')||'scroll',theme:localStorage.getItem('nt_theme')||'dark'};
function save(){localStorage.setItem('nt_favorites',JSON.stringify(state.favorites));localStorage.setItem('nt_history',JSON.stringify(state.history));localStorage.setItem('nt_reader',state.reader);localStorage.setItem('nt_theme',state.theme)}
function cover(i){return palettes[i%palettes.length]}
function renderCards(id,list){$(id).innerHTML=list.map((x,i)=>`<article class="card" data-id="${x[0]}" data-title="${x[1].toLowerCase()}"><div class="cover" style="background:${cover(i)}"><span class="tag">${i<2?'NEW':'CH.'+(80+i*14)}</span><b>${x[1]}</b></div><div class="info"><h3>${x[1]}</h3><p>${x[2]}</p><div class="foot"><span class="rating">★ ${x[4]}</span><span>♨ ${x[3]}</span></div></div></article>`).join('')}
function allItems(){return [...DATA.popular,...DATA.manhwa,...DATA.novel]}
function renderTop(kind='popular'){const list=DATA[kind]||DATA.popular;$('#top10').innerHTML=list.slice(0,10).map((x,i)=>`<button class="toprow" data-id="${x[0]}" data-action="openComic"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="topcover" style="background:${cover(i)}"></span><span><b>${x[1]}</b><small>${x[2]}</small></span><span class="score">★ ${x[4]}</span><span class="views">${x[3]}</span></button>`).join('')}
function renderNotices(){$('#noticeList').innerHTML=[['⚡','Chapter baru telah tersedia!','Solo Leveling · Chapter 210'],['♡','Komik favoritmu update 50%!','One Piece · Special Sale'],['▤','Ada balasan di komentar kamu','Jujutsu Kaisen · Chapter 193']].map(x=>`<div class="notice"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(title,html){$('#modalBody').innerHTML=`<small>NECROTOON</small><h2>${title}</h2>${html}`;$('#modal').classList.add('open')}
function find(id){return allItems().find(x=>x[0]===id)}
function comicModal(id){const x=find(id)||DATA.popular[0],fav=state.favorites.includes(x[0]),hist=state.history.includes(x[0]);openModal(x[1],`<p>${x[2]} · ★ ${x[4]} · ${x[3]} pembaca</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="primary" data-action="read" data-id="${x[0]}">Mulai Baca →</button><button class="ghost" data-action="favorite" data-id="${x[0]}">${fav?'♥ Hapus Favorit':'♡ Tambah Favorit'}</button></div><div style="margin-top:20px;padding:14px;border:1px solid #153b63;border-radius:14px"><b>Chapter Terbaru</b><p>Chapter 210 · 209 · 208 · 207 · 206</p>${hist?'<small style="color:#19c9ff">✓ Ada di riwayat baca</small>':''}</div>`)}
function reader(id){const x=find(id)||DATA.popular[0];if(!state.history.includes(id)){state.history.unshift(id);state.history=state.history.slice(0,20);save()}openModal(`Reader · ${x[1]}`,`<div style="background:#000;border-radius:14px;min-height:280px;display:grid;place-items:center;text-align:center;padding:30px"><div><div style="font-size:55px;color:#15caff">${state.reader==='scroll'?'▤':state.reader==='tap'?'◉':state.reader==='page'?'▣':'◌'}</div><h3>Chapter 210</h3><p style="color:#7890aa">Demo reader frontend — struktur chapter siap disambungkan ke sumber gambar/API.</p><button class="primary" data-action="nextChapter" data-id="${id}">Chapter Berikutnya →</button></div></div>`)}
function profile(){openModal('Profil Necro',`<div style="display:flex;gap:14px;align-items:center"><div class="avatar">N</div><div><b>Guest Reader</b><p>Login untuk menyimpan progress ke cloud.</p></div></div><button class="primary" data-action="login">Login / Register →</button>`)}
function notifications(){openModal('Notifikasi',`<div class="noticeList">${$('#noticeList').innerHTML}</div><button class="primary" data-action="clearNotifications">Tandai Semua Dibaca</button>`)}
function route(r){if(r==='home'){window.scrollTo({top:0,behavior:'smooth'});return}if(r==='favorites'){openModal('Favorit',state.favorites.length?state.favorites.map(id=>{const x=find(id);return `<button style="display:block;width:100%;text-align:left;padding:12px;border-bottom:1px solid #12314f" data-action="openComic" data-id="${id}">${x?x[1]:id}</button>`}).join(''):'<p>Belum ada favorit. Buka komik lalu tekan Tambah Favorit.</p>');return}if(r==='history'){openModal('Riwayat Baca',state.history.length?state.history.map(id=>{const x=find(id);return `<button style="display:block;width:100%;text-align:left;padding:12px;border-bottom:1px solid #12314f" data-action="read" data-id="${id}">↻ ${x?x[1]:id}</button>`}).join(''):'<p>Riwayat baca masih kosong.</p>');return}if(r==='notifications'){notifications();return}if(r==='settings'){openModal('Pengaturan',`<p>Preferensi reader tersimpan di perangkat ini.</p><button class="ghost" data-action="theme">Ganti Tema</button><button class="ghost" data-action="clearData">Reset Data Demo</button>`);return}if(r==='library'||r==='manhwa'||r==='novel'){const el=$(r==='library'?'#popularCards':r==='manhwa'?'#manhwaCards':'#novelCards');el.scrollIntoView({behavior:'smooth',block:'center'});}}
function theme(){state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.theme==='light');save();toast(state.theme==='light'?'Mode terang aktif':'Mode gelap aktif')}
function favorite(id){if(state.favorites.includes(id))state.favorites=state.favorites.filter(x=>x!==id);else state.favorites.unshift(id);save();comicModal(id);toast(state.favorites.includes(id)?'Ditambahkan ke Favorit ♥':'Dihapus dari Favorit')}
function setup(){renderCards('#popularCards',DATA.popular);renderCards('#manhwaCards',DATA.manhwa);renderCards('#novelCards',DATA.novel);renderTop();renderNotices();document.body.classList.toggle('light',state.theme==='light');$$('[data-route]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();route(b.dataset.route);$$('[data-route]').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('open')}));$$('[data-tab]').forEach(b=>b.onclick=()=>{ $$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTop(b.dataset.tab==='komik'?'popular':b.dataset.tab)});}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action,id=a.dataset.id;if(act==='openComic')comicModal(id);if(act==='read')reader(id);if(act==='favorite')favorite(id);if(act==='profile')profile();if(act==='notifications')notifications();if(act==='theme')theme();if(act==='premium')openModal('Necro Premium','<p>Premium demo aktif. Nanti kita sambungkan ke sistem pembayaran.</p><button class="primary" data-action="login">Mulai Premium →</button>');if(act==='discord')openModal('NecroToon Community','<p>Link Discord siap dimasukkan. Untuk sekarang ini adalah preview interaksi.</p>');if(act==='continue')reader('solo');if(act==='login')openModal('Login','<p>Form login/register akan menjadi tahap backend berikutnya.</p><input style="width:100%;padding:12px;border-radius:10px;border:1px solid #19436b;background:#031126;color:white;margin:6px 0" placeholder="Email"><input type="password" style="width:100%;padding:12px;border-radius:10px;border:1px solid #19436b;background:#031126;color:white;margin:6px 0" placeholder="Password"><button class="primary">Masuk</button>');if(act==='clearNotifications')toast('Semua notifikasi ditandai sudah dibaca');if(act==='clearData'){localStorage.removeItem('nt_favorites');localStorage.removeItem('nt_history');toast('Data demo direset');setTimeout(()=>location.reload(),500)}if(act==='nextChapter')toast('Chapter 211 dipilih');}
const c=e.target.closest('.card');if(c&&!a)comicModal(c.dataset.id);if(e.target.id==='menuBtn'){$('#sidebar').classList.toggle('open');$('#backdrop').classList.toggle('show')}if(e.target.id==='backdrop'){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}if(e.target.id==='mobileSearch'){$('#search').focus();window.scrollTo({top:0,behavior:'smooth'})}if(e.target.id==='closeModal'||e.target.closest('#closeModal'))$('#modal').classList.remove('open');const rm=e.target.closest('[data-reader]');if(rm){state.reader=rm.dataset.reader;save();$$('[data-reader]').forEach(x=>x.classList.toggle('active',x===rm));toast('Mode baca: '+state.reader)}const rt=e.target.closest('[data-reader-theme]');if(rt){$$('[data-reader-theme]').forEach(x=>x.classList.remove('active'));rt.classList.add('active');toast('Tema reader diperbarui')}});
$('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();$$('.card').forEach(c=>c.style.display=!q||c.dataset.title.includes(q)?'':'none')});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')$('#modal').classList.remove('open')});window.addEventListener('scroll',()=>{const d=document.documentElement;$('#progress').style.width=(d.scrollTop/(d.scrollHeight-d.clientHeight)*100)+'%' });$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')});setup();
