const DATA={
 popular:[['solo','Solo Leveling','Action · Adventure · Fantasy','2.4M','9.8','210'],['one','One Piece','Action · Adventure · Comedy','1.8M','9.7','1160'],['blue','Blue Lock','Sports · Psychological','1.2M','9.5','320'],['jjk','Jujutsu Kaisen','Action · Supernatural','1.5M','9.6','271'],['tba','The Beginning After The End','Action · Fantasy · Reincarnation','908K','9.4','220'],['mage','Versatile Mage','Action · Fantasy · School','760K','9.3','1240']],
 manhwa:[['hua','Return of the Mount Hua','Action · Murim · Comedy','1.1M','9.6','145'],['extra',"The Extra's Academy Survival Guide",'Fantasy · School · Action','840K','9.5','98'],['villain',"I Became the Villain's Son",'Drama · Fantasy · Romance','620K','9.2','84'],['sss','SSS-Class Suicide Hunter','Action · Fantasy · Tower','780K','9.7','119'],['infinite','Infinite Mage','Fantasy · Magic · Adventure','540K','9.3','86'],['tower','Tower of God','Adventure · Fantasy · Mystery','650K','9.1','650']],
 novel:[['reverend','Reverend Insanity','Action · Fantasy · Cultivation','1.2M','9.6','2334'],['mysteries','Lord of the Mysteries','Mystery · Supernatural · Steampunk','980K','9.5','1432'],['orv','Omniscient Reader','Action · Fantasy · Apocalypse','860K','9.4','730'],['moon','The Legendary Moonlight Sculptor','Action · Fantasy · Game','760K','9.3','1690'],['demons','Tales of Demons and Gods','Action · Fantasy · Reincarnation','690K','9.2','720'],['martial','Martial Peak','Action · Adventure · Cultivation','620K','9.1','6000']]
};
const palettes=['linear-gradient(145deg,#101d55,#1468ff,#00d8ff)','linear-gradient(145deg,#8e1b18,#ffae22,#1679ff)','linear-gradient(145deg,#071f67,#1b68ff,#17c8ff)','linear-gradient(145deg,#240b38,#a62660,#ff5b30)','linear-gradient(145deg,#18344e,#50a8a9,#c6ecff)','linear-gradient(145deg,#2a174b,#3b64ff,#ffb4ff)'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={favorites:JSON.parse(localStorage.getItem('nt_favorites')||'[]'),history:JSON.parse(localStorage.getItem('nt_history')||'[]'),reader:localStorage.getItem('nt_reader')||'scroll',theme:localStorage.getItem('nt_theme')||'dark',readChapter:JSON.parse(localStorage.getItem('nt_chapters')||'{}')};
function save(){localStorage.setItem('nt_favorites',JSON.stringify(state.favorites));localStorage.setItem('nt_history',JSON.stringify(state.history));localStorage.setItem('nt_reader',state.reader);localStorage.setItem('nt_theme',state.theme);localStorage.setItem('nt_chapters',JSON.stringify(state.readChapter))}
function cover(i){return palettes[i%palettes.length]}
function renderCards(id,list){$(id).innerHTML=list.map((x,i)=>`<article class="card" data-id="${x[0]}" data-title="${x[1].toLowerCase()}"><div class="cover c${i%6}" style="background:${cover(i)}"><span class="tag">${i<2?'NEW':'CH. '+x[5]}</span><div class="coverArt"><span>${x[0].slice(0,2).toUpperCase()}</span></div><b>${x[1]}</b></div><div class="info"><h3>${x[1]}</h3><p>${x[2]}</p><div class="foot"><span class="rating">★ ${x[4]}</span><span>♨ ${x[3]}</span></div></div></article>`).join('')}
function allItems(){return [...DATA.popular,...DATA.manhwa,...DATA.novel]}
function find(id){return allItems().find(x=>x[0]===id)}
function renderTop(kind='popular'){const list=DATA[kind]||DATA.popular;$('#top10').innerHTML=list.map((x,i)=>`<button class="toprow" data-id="${x[0]}" data-action="openComic"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="topcover" style="background:${cover(i)}"><b>${x[0].slice(0,2).toUpperCase()}</b></span><span><b>${x[1]}</b><small>${x[2]}</small></span><span class="score">★ ${x[4]}</span><span class="views">${x[3]}</span></button>`).join('')}
function renderNotices(){$('#noticeList').innerHTML=[['⚡','Chapter baru telah tersedia!','Solo Leveling · Chapter 210'],['♡','Komik favoritmu update!','One Piece · Chapter 1160'],['▤','Ada balasan di komentar kamu','Jujutsu Kaisen · Chapter 193']].map(x=>`<div class="notice"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(title,html,wide=false){$('#modalBody').innerHTML=`<small>NECROTOON</small><h2>${title}</h2>${html}`;$('#modalBox').classList.toggle('wide',wide);$('#modal').classList.add('open')}
function comicModal(id){const x=find(id)||DATA.popular[0],fav=state.favorites.includes(x[0]),last=state.readChapter[x[0]]||0;const chapters=Array.from({length:8},(_,i)=>x[5]-i);openModal(x[1],`<div class="detailGrid"><div class="detailCover" style="background:${cover(2)}"><span>${x[0].slice(0,2).toUpperCase()}</span></div><div><p>${x[2]}</p><div class="detailStats"><span>★ ${x[4]}</span><span>♨ ${x[3]}</span><span>▣ ${x[5]} CH.</span></div><p>Ikuti perjalanan <b>${x[1]}</b> dalam dunia penuh konflik, kekuatan, dan misteri. Halaman ini adalah demo frontend dan siap dihubungkan ke API/database.</p><div class="heroBtns"><button class="primary" data-action="read" data-id="${x[0]}">Mulai Baca →</button><button class="ghost" data-action="favorite" data-id="${x[0]}">${fav?'♥ Hapus Favorit':'♡ Tambah Favorit'}</button></div>${last?`<small class="resume">✓ Lanjut dari Chapter ${last}</small>`:''}</div></div><div class="chapterHead"><b>Chapter Terbaru</b><span>${chapters.length} tersedia</span></div><div class="chapterList">${chapters.map((ch,i)=>`<button data-action="readChapter" data-id="${x[0]}" data-chapter="${ch}"><span>Chapter ${ch}</span><small>${i===0?'Terbaru':i<3?'Baru':'Tersedia'}</small><b>→</b></button>`).join('')}</div>`,true)}
function reader(id,chapter){const x=find(id)||DATA.popular[0];const ch=chapter||state.readChapter[id]||Number(x[5]);state.readChapter[id]=ch;state.history=[id,...state.history.filter(v=>v!==id)].slice(0,20);save();const pages=Array.from({length:6},(_,i)=>`<div class="readerPage" style="background:${palettes[(i+2)%palettes.length]}"><span>${x[0].slice(0,2).toUpperCase()}</span><b>${x[1]}</b><small>Demo Page ${i+1}</small></div>`).join('');openModal(`Chapter ${ch} · ${x[1]}`,`<div class="readerToolbar"><button class="ghost" data-reader="scroll">Scroll</button><button class="ghost" data-reader="page">Page</button><button class="ghost" data-reader="tap">Tap</button><button class="ghost" data-reader="auto">Auto</button></div><div class="readerStage ${state.reader}">${pages}</div><div class="readerNav"><button class="ghost" data-action="chapterNav" data-id="${id}" data-dir="-1">← Prev</button><span>Chapter ${ch}</span><button class="primary" data-action="chapterNav" data-id="${id}" data-dir="1">Next →</button></div>`,true)}
function profile(){openModal('Profil Necro',`<div class="profileBox"><div class="avatar big">N</div><div><b>Guest Reader</b><p>Login untuk menyimpan progress ke cloud dan sinkronisasi lintas perangkat.</p></div></div><button class="primary full" data-action="login">Login / Register →</button>`)}
function notifications(){openModal('Notifikasi',`<div class="noticeList">${$('#noticeList').innerHTML}</div><button class="primary" data-action="clearNotifications">Tandai Semua Dibaca</button>`)}
function listModal(title,items,action,empty){openModal(title,items.length?items.map(id=>{const x=find(id);return `<button class="listRow" data-action="${action}" data-id="${id}"><span class="miniCover" style="background:${cover(1)}">${x?x[0].slice(0,2).toUpperCase():''}</span><span><b>${x?x[1]:id}</b><small>${x?x[2]:''}</small></span><strong>→</strong></button>`}).join(''):empty)}
function route(r){if(r==='home'){closeModal();window.scrollTo({top:0,behavior:'smooth'});return}if(r==='favorites'){listModal('Favorit',state.favorites,'openComic','Belum ada favorit. Buka komik lalu tekan Tambah Favorit.');return}if(r==='history'){listModal('Riwayat Baca',state.history,'read','Riwayat baca masih kosong.');return}if(r==='notifications'){notifications();return}if(r==='settings'){openModal('Pengaturan',`<div class="settingRow"><span>Tema Website</span><button class="ghost" data-action="theme">${state.theme==='dark'?'Dark':'Light'}</button></div><div class="settingRow"><span>Mode Reader</span><select id="readerSelect"><option value="scroll">Scroll</option><option value="page">Page</option><option value="tap">Tap</option><option value="auto">Auto</option></select></div><button class="ghost" data-action="clearData">Reset Data Demo</button>`);return}if(r==='library'||r==='manhwa'||r==='novel'){const el=$(r==='library'?'#popularCards':r==='manhwa'?'#manhwaCards':'#novelCards');el.scrollIntoView({behavior:'smooth',block:'center'});}}
function theme(){state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.theme==='light');save();toast(state.theme==='light'?'Mode terang aktif':'Mode gelap aktif')}
function favorite(id){if(state.favorites.includes(id))state.favorites=state.favorites.filter(x=>x!==id);else state.favorites.unshift(id);save();comicModal(id);toast(state.favorites.includes(id)?'Ditambahkan ke Favorit ♥':'Dihapus dari Favorit')}
function doSearch(q){q=q.toLowerCase().trim();const all=allItems().filter(x=>x[1].toLowerCase().includes(q)||x[2].toLowerCase().includes(q));const box=$('#searchResults');if(!box)return;if(!q){box.innerHTML='';return}let html='<div class=\"searchResultHead\"><b>'+all.length+' hasil untuk “'+q+'”</b></div>';if(!all.length)html+='<p class=\"empty\">Tidak ada judul yang cocok.</p>';else html+=all.map(x=>'<button class=\"searchResult\" data-action=\"openComic\" data-id=\"'+x[0]+'\"><span class=\"miniCover\" style=\"background:'+cover(2)+'\">'+x[0].slice(0,2).toUpperCase()+'</span><span><b>'+x[1]+'</b><small>'+x[2]+' · ★ '+x[4]+'</small></span><strong>→</strong></button>').join('');box.innerHTML=html}

function setup(){renderCards('#popularCards',DATA.popular);renderCards('#manhwaCards',DATA.manhwa);renderCards('#novelCards',DATA.novel);renderTop();renderNotices();document.body.classList.toggle('light',state.theme==='light');$$('[data-route]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();route(b.dataset.route);$$('[data-route]').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}));$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTop(b.dataset.tab==='komik'?'popular':b.dataset.tab)});}
function closeModal(){$('#modal').classList.remove('open')}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action,id=a.dataset.id;if(act==='openComic')comicModal(id);if(act==='read')reader(id);if(act==='readChapter')reader(id,Number(a.dataset.chapter));if(act==='favorite')favorite(id);if(act==='profile')profile();if(act==='notifications')notifications();if(act==='theme')theme();if(act==='premium')openModal('Necro Premium','<p>Premium demo aktif. Nanti kita sambungkan ke sistem pembayaran.</p><button class="primary" data-action="login">Mulai Premium →</button>');if(act==='discord')openModal('NecroToon Community','<p>Link Discord siap dimasukkan. Untuk sekarang ini adalah preview interaksi.</p>');if(act==='continue')reader('solo');if(act==='login')openModal('Login / Register','<input class="formInput" placeholder="Nama pengguna"><input class="formInput" placeholder="Email"><input type="password" class="formInput" placeholder="Password"><button class="primary full" data-action="fakeLogin">Masuk / Daftar</button>');if(act==='fakeLogin'){closeModal();toast('Akun demo berhasil masuk');}if(act==='clearNotifications')toast('Semua notifikasi ditandai sudah dibaca');if(act==='clearData'){localStorage.clear();toast('Data demo direset');setTimeout(()=>location.reload(),500)}if(act==='chapterNav'){const x=find(id),ch=(state.readChapter[id]||Number(x?.[5]||1))+Number(a.dataset.dir);reader(id,Math.max(1,ch));}}
const c=e.target.closest('.card');if(c&&!a)comicModal(c.dataset.id);if(e.target.id==='menuBtn'){$('#sidebar').classList.toggle('open');$('#backdrop').classList.toggle('show')}if(e.target.id==='backdrop'){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}if(e.target.id==='mobileSearch'){const sw=$('.searchWrap');sw.classList.toggle('mobileSearchOpen');$('#search').focus();window.scrollTo({top:0,behavior:'smooth'})}if(e.target.id==='closeModal'||e.target.closest('#closeModal'))closeModal();const rm=e.target.closest('[data-reader]');if(rm&&rm.tagName==='BUTTON'){state.reader=rm.dataset.reader;save();$$('[data-reader]').forEach(x=>x.classList.toggle('active',x===rm));toast('Mode baca: '+state.reader)}const rt=e.target.closest('[data-reader-theme]');if(rt){$$('[data-reader-theme]').forEach(x=>x.classList.remove('active'));rt.classList.add('active');toast('Tema reader diperbarui')}});
$('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();$$('.card').forEach(c=>c.style.display=!q||c.dataset.title.includes(q)?'':'none');doSearch(q)});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')closeModal()});window.addEventListener('scroll',()=>{const d=document.documentElement;const max=d.scrollHeight-d.clientHeight;$('#progress').style.width=(max?d.scrollTop/max*100:0)+'%'});$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});setup();
